### ISSUE TITLE
Build fail on OSX due to Swig update

### ISSUE THREAD

**Issue by dbogdanov** [MTG/gaia#35]
Building Gaia with python bindings fails using the most recent swig 3.0.8 on OSX. Swig 3.0.4 is reported to work fine. 
```
/usr/local/bin/swig -c++ -python -w451 -o /Users/dbogdanov/mtg/gaia/build/src/bindings/gaia2.swigwrap_1.cxx -I/Users/dbogdanov/mtg/gaia/build/src -I/Users/dbogdanov/mtg/gaia/src -I/Users/dbogdanov/mtg/gaia/build/src/bindings -I/Users/dbogdanov/mtg/gaia/src/bindings -I/Users/dbogdanov/mtg/gaia/build/src/metrics -I/Users/dbogdanov/mtg/gaia/src/metrics -I/Users/dbogdanov/mtg/gaia/build/src/3rdparty -I/Users/dbogdanov/mtg/gaia/src/3rdparty -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/qt/4.8.7_2/include -I/usr/local/Cellar/qt/4.8.7_2/include/QtCore -DGAIA_VERSION="2.4.4" -DGAIA_GIT_SHA="v2.4.4-17-gff46634" -DHAVE_QTUITOOLS_DEBUG=1 -DHAVE_QTCORE=1 -DHAVE_QTGUI=1 -DHAVE_QTUITOOLS=1 -DHAVE_QTNETWORK=1 -DHAVE_QTOPENGL=1 -DHAVE_QTSQL=1 -DHAVE_QTSVG=1 -DHAVE_QTTEST=1 -DHAVE_QTXML=1 -DHAVE_QTXMLPATTERNS=1 -DHAVE_QTWEBKIT=1 -DHAVE_QTHELP=1 -DHAVE_QTSCRIPT=1 -DHAVE_QTDECLARATIVE=1 -DPYTHONDIR="/usr/local/lib/python2.7/site-packages" -DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages" -DHAVE_PYTHON_H=1 -DNDEBUG -DQT_SHARED ../src/bindings/gaia.swig
Assertion failed: (!Getattr(n, "defaultargs")), function update_defaultargs, file parser.y, line 667.
Abort trap: 6
```

**Comment by alastair** [comment]
looks similar to https://github.com/MTG/gaia/issues/39 too

**Comment by dbogdanov** [comment]
The newest Ubuntu 16 contains swig 3.0.8 as well.

**Comment by dbogdanov** [comment]
This issue has been fixed by swig, their next release may come out soon.

**Comment by alastair** [comment]
3.0.9 was tagged on May 29, but it's not listed on their download page yet. I tested and it compiles the bindings fine.

**Comment by dbogdanov** [comment]
👏

**Comment by dbogdanov** [comment]
Still not in homebrew... MacPorts has already added 3.0.9 but without swig-python

**Comment by alastair** [comment]
I still see a problem with importing the compiled package from within python.

Somewhere between swig 2.0.11 (what we have on the AB server) and 3.0.9 (which I installed), they added a new method of importing `_gaia2.so` when you `import gaia`. I get this error:

```
In [7]: import gaia2

/home/alastair/code/acousticbrainz-server/env/local/lib/python2.7/site-packages/gaia2/__init__.py in <module>()
     18         print mname
     19         return importlib.import_module(mname)
---> 20     _gaia2 = swig_import_helper()
     21     del swig_import_helper
     22 elif version_info >= (2, 6, 0):

/home/alastair/code/acousticbrainz-server/env/local/lib/python2.7/site-packages/gaia2/__init__.py in swig_import_helper()
     17         mname = '.'.join((pkg, '_gaia2')).lstrip('.')
     18         print mname
---> 19         return importlib.import_module(mname)
     20     _gaia2 = swig_import_helper()
     21     del swig_import_helper

/usr/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: No module named _gaia2
```

The `importlib.import_module` doesn't seem to be looking in the right directory for the so file. The "old" import code, which now only runs on python 2.6 seems to work fine. I don't know why this change was added. It'll probably affect essentia too.

**Comment by alastair** [comment]
The broken import code in question is
```
if version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_gaia2')).lstrip('.')
        return importlib.import_module(mname)
    _gaia2 = swig_import_helper()
    del swig_import_helper
```
I notice that the swig code as compiled provides `gaia2.py` and `_gaia2.so`. If these were both placed in `site-packages` then the import would work, but I see in the wscript we rename this file:

    bld.install_as('${PYTHONDIR}/gaia2/__init__.py', 'gaia2.py')

Perhaps the way that we're installing gaia into the python dir is no longer correct.

**Comment by alastair** [comment]
To follow up again, this was changed in 3.0.10, which was just released with these notes:
> This release fixes a couple of important regressions in SWIG-3.0.9 for smart pointers and importing Python modules.

However, I just tested it and the way that we import gaia still isn't fixed with these changes

**Comment by dbogdanov** [comment]
Install location for gaia2.py is correct. Packages installed into the python dir always have the same structure: ```site-packages/packagename/__init__.py```. The issue is fixed by installing ```_gaia2.so``` directly to ```site-packages```. 

The issue does not affect Essentia.

**Comment by dbogdanov** [comment]
So, we still got a problem on ubuntu 16.04, and unfortunately ubuntu 16.10 will also ship swig 3.0.8.
